{% set name = "plams" %}
{% set version = "2026.102" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/plams-{{ version }}.tar.gz
  sha256: d70ad1d6d7a443fe631a679af57553f6967043225ba0a8f0cbe3d633c0d0b8c5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - dill >=0.2.4
    - natsort
    - numpy <2
    - scipy
    - python >={{ python_min }}

test:
  imports:
    - scm.plams
    - scm.plams.core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.scm.com/doc/plams/
  summary: Python Library for Automating Molecular Simulations
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
