{% set name = "plams" %}
{% set version = "2024.103" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plams-{{ version }}.tar.gz
  sha256: 0ee90296b44c71e8ab06ac43a575a6dc764a20852f6a12ad7b2a9621e55ac1a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - dill >=0.2.4
    - numpy
    - python >=3.7

test:
  imports:
    - scm.plams
    - scm.plams.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.scm.com/doc/plams/
  summary: Python Library for Automating Molecular Simulations
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
