{% set name = "plams" %}
{% set version = "2024.105" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plams-{{ version }}.tar.gz
  sha256: d93dfc4126a142ed8541610ab04a9ae048601c4c19f1fa788bff46c81a0d1e3e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - dill >=0.2.4
    - natsort
    - numpy <2
    - scipy
    - python >=3.7

test:
  imports:
    - scm.plams
    - scm.plams.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.scm.com/doc/plams/
  summary: Python Library for Automating Molecular Simulations
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
